// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoK54YtSp0ewrTj34i2rPe1oL0GRnLJ7c',
    appId: '1:1044385788435:web:35abe05a8b9b7c8e77c5e6',
    messagingSenderId: '1044385788435',
    projectId: 'musaf-62fb2',
    authDomain: 'musaf-62fb2.firebaseapp.com',
    storageBucket: 'musaf-62fb2.firebasestorage.app',
    measurementId: 'G-1SGXE5M22H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAm2Mpe19bPpITrdjomj5IoIsVzseWZvE0',
    appId: '1:1044385788435:android:014bbe589800e15677c5e6',
    messagingSenderId: '1044385788435',
    projectId: 'musaf-62fb2',
    storageBucket: 'musaf-62fb2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBreZmZuFtWIrvTSXZqyLmuTm_s3WA8DPM',
    appId: '1:1044385788435:ios:69f1e9a265eaca6377c5e6',
    messagingSenderId: '1044385788435',
    projectId: 'musaf-62fb2',
    storageBucket: 'musaf-62fb2.firebasestorage.app',
    iosBundleId: 'com.example.musafPro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBreZmZuFtWIrvTSXZqyLmuTm_s3WA8DPM',
    appId: '1:1044385788435:ios:69f1e9a265eaca6377c5e6',
    messagingSenderId: '1044385788435',
    projectId: 'musaf-62fb2',
    storageBucket: 'musaf-62fb2.firebasestorage.app',
    iosBundleId: 'com.example.musafPro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCoK54YtSp0ewrTj34i2rPe1oL0GRnLJ7c',
    appId: '1:1044385788435:web:6459376756dd523177c5e6',
    messagingSenderId: '1044385788435',
    projectId: 'musaf-62fb2',
    authDomain: 'musaf-62fb2.firebaseapp.com',
    storageBucket: 'musaf-62fb2.firebasestorage.app',
    measurementId: 'G-PEGRHBVK7G',
  );
}
